/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDownloadsRouteImport } from './routes/_app.downloads'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAtsRouteImport } from './routes/_app.ats'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppResumesIndexRouteImport } from './routes/_app.resumes.index'
import { Route as AppResumesNewRouteImport } from './routes/_app.resumes.new'
import { Route as AppResumesIdIndexRouteImport } from './routes/_app.resumes.$id.index'
import { Route as AppResumesIdPreviewRouteImport } from './routes/_app.resumes.$id.preview'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsRoute = AppAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIndexRoute = AppResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesNewRoute = AppResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIdIndexRoute = AppResumesIdIndexRouteImport.update({
  id: '/resumes/$id/',
  path: '/resumes/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIdPreviewRoute = AppResumesIdPreviewRouteImport.update({
  id: '/resumes/$id/preview',
  path: '/resumes/$id/preview',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AppAiRoute
  '/ats': typeof AppAtsRoute
  '/dashboard': typeof AppDashboardRoute
  '/downloads': typeof AppDownloadsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/resumes/new': typeof AppResumesNewRoute
  '/resumes/': typeof AppResumesIndexRoute
  '/resumes/$id/preview': typeof AppResumesIdPreviewRoute
  '/resumes/$id/': typeof AppResumesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai': typeof AppAiRoute
  '/ats': typeof AppAtsRoute
  '/dashboard': typeof AppDashboardRoute
  '/downloads': typeof AppDownloadsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/resumes/new': typeof AppResumesNewRoute
  '/resumes': typeof AppResumesIndexRoute
  '/resumes/$id/preview': typeof AppResumesIdPreviewRoute
  '/resumes/$id': typeof AppResumesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/ats': typeof AppAtsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/resumes/new': typeof AppResumesNewRoute
  '/_app/resumes/': typeof AppResumesIndexRoute
  '/_app/resumes/$id/preview': typeof AppResumesIdPreviewRoute
  '/_app/resumes/$id/': typeof AppResumesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai'
    | '/ats'
    | '/dashboard'
    | '/downloads'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/resumes/new'
    | '/resumes/'
    | '/resumes/$id/preview'
    | '/resumes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai'
    | '/ats'
    | '/dashboard'
    | '/downloads'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/resumes/new'
    | '/resumes'
    | '/resumes/$id/preview'
    | '/resumes/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/ai'
    | '/_app/ats'
    | '/_app/dashboard'
    | '/_app/downloads'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/resumes/new'
    | '/_app/resumes/'
    | '/_app/resumes/$id/preview'
    | '/_app/resumes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats': {
      id: '/_app/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AppAtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/': {
      id: '/_app/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AppResumesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/new': {
      id: '/_app/resumes/new'
      path: '/resumes/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof AppResumesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/$id/': {
      id: '/_app/resumes/$id/'
      path: '/resumes/$id'
      fullPath: '/resumes/$id/'
      preLoaderRoute: typeof AppResumesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/$id/preview': {
      id: '/_app/resumes/$id/preview'
      path: '/resumes/$id/preview'
      fullPath: '/resumes/$id/preview'
      preLoaderRoute: typeof AppResumesIdPreviewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAtsRoute: typeof AppAtsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppResumesNewRoute: typeof AppResumesNewRoute
  AppResumesIndexRoute: typeof AppResumesIndexRoute
  AppResumesIdPreviewRoute: typeof AppResumesIdPreviewRoute
  AppResumesIdIndexRoute: typeof AppResumesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAtsRoute: AppAtsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppResumesNewRoute: AppResumesNewRoute,
  AppResumesIndexRoute: AppResumesIndexRoute,
  AppResumesIdPreviewRoute: AppResumesIdPreviewRoute,
  AppResumesIdIndexRoute: AppResumesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
